
package kz.dara.gbdulNewService.sync.v10.interfaces;



import kz.dara.gbdulNewService.sync.v10.types.request.SyncSendMessageRequest;
import kz.dara.gbdulNewService.sync.v10.types.response.SyncSendMessageResponse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * Интерфейс для работы с синхронным каналом
 * <p>
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "ISyncChannel", targetNamespace = "http://bip.bee.kz/SyncChannel/v10/Interfaces")
@XmlSeeAlso({
//        kz.dara.laborHistoryService.sync.v10.types.request.ObjectFactory.class,
//        kz.dara.laborHistoryService.sync.v10.types.response.ObjectFactory.class,
//        ObjectFactory.class

})
public interface ISyncChannel {


    /**
     * Метод отправки сообщения по синхронному каналу
     *
     * @param request
     * @return returns kz.bee.bip.syncchannel.v10.types.response.SyncSendMessageResponse
     * @throws SendMessageSendMessageFaultMsg exception
     */
    @WebMethod(operationName = "SendMessage")
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "SendMessage", targetNamespace = "http://bip.bee.kz/SyncChannel/v10/Types", className = "kz.bee.bip.syncchannel.v10.types.SendMessage")
    @ResponseWrapper(localName = "SendMessageResponse", targetNamespace = "http://bip.bee.kz/SyncChannel/v10/Types", className = "kz.bee.bip.syncchannel.v10.types.SendMessageResponse")
    public SyncSendMessageResponse sendMessage(
            @WebParam(name = "request", targetNamespace = "")
            SyncSendMessageRequest request)
            throws SendMessageSendMessageFaultMsg
    ;

}
