
package kz.dara.gbdulNewService.sync.v10.interfaces;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ISyncChannelHttpService", targetNamespace = "http://bip.bee.kz/SyncChannel/v10/Interfaces", wsdlLocation = "http://192.168.81.2/bip-sync-wss-gost/?wsdl")
public class ISyncChannelHttpService
    extends Service
{

    private final static URL ISYNCCHANNELHTTPSERVICE_WSDL_LOCATION;
    private final static WebServiceException ISYNCCHANNELHTTPSERVICE_EXCEPTION;
    private final static QName ISYNCCHANNELHTTPSERVICE_QNAME = new QName("http://bip.bee.kz/SyncChannel/v10/Interfaces", "ISyncChannelHttpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.81.2/bip-sync-wss-gost/");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ISYNCCHANNELHTTPSERVICE_WSDL_LOCATION = url;
        ISYNCCHANNELHTTPSERVICE_EXCEPTION = e;
    }

    public ISyncChannelHttpService() {
        super(__getWsdlLocation(), ISYNCCHANNELHTTPSERVICE_QNAME);
    }

    public ISyncChannelHttpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ISYNCCHANNELHTTPSERVICE_QNAME, features);
    }

    public ISyncChannelHttpService(URL wsdlLocation) {
        super(wsdlLocation, ISYNCCHANNELHTTPSERVICE_QNAME);
    }

    public ISyncChannelHttpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ISYNCCHANNELHTTPSERVICE_QNAME, features);
    }

    public ISyncChannelHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ISyncChannelHttpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ISyncChannel
     */
    @WebEndpoint(name = "SyncChannelHttpPort")
    public ISyncChannel getSyncChannelHttpPort() {
        return super.getPort(new QName("http://bip.bee.kz/SyncChannel/v10/Interfaces", "SyncChannelHttpPort"), ISyncChannel.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISyncChannel
     */
    @WebEndpoint(name = "SyncChannelHttpPort")
    public ISyncChannel getSyncChannelHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://bip.bee.kz/SyncChannel/v10/Interfaces", "SyncChannelHttpPort"), ISyncChannel.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ISYNCCHANNELHTTPSERVICE_EXCEPTION!= null) {
            throw ISYNCCHANNELHTTPSERVICE_EXCEPTION;
        }
        return ISYNCCHANNELHTTPSERVICE_WSDL_LOCATION;
    }

}
