//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.15 at 12:37:26 PM ALMT 
//


package kz.dara.gbdulNewService.sync;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the kz.b10.smartbridge package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SendMessageResponse_QNAME = new QName("http://smartbridge.b10.kz", "sendMessageResponse");
    private final static QName _SendMessageRequest_QNAME = new QName("http://smartbridge.b10.kz", "sendMessageRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: kz.b10.smartbridge
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     */
    @XmlElementDecl(namespace = "http://smartbridge.b10.kz", name = "sendMessageResponse")
    public JAXBElement<Object> createSendMessageResponse(Object value) {
        return new JAXBElement<Object>(_SendMessageResponse_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     */
    @XmlElementDecl(namespace = "http://smartbridge.b10.kz", name = "sendMessageRequest")
    public JAXBElement<Object> createSendMessageRequest(Object value) {
        return new JAXBElement<Object>(_SendMessageRequest_QNAME, Object.class, null, value);
    }

}
